services:
  # don't touch
  # nextapp:
  #   container_name: nextapp
  #   image: nextapp:1.0.0
  #   build:
  #     context: ./frontend
  #     dockerfile: next.dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
  #   depends_on:
  #     - goapp
  # goapp:
  #   container_name: goapp
  #   image: goapp:1.0.0
  #   build:
  #     context: ./backend
  #     dockerfile: go.dockerfile
  #   environment:
  #     DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  postgres:
    image: postgres:14.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - net
    container_name: postgres-com
    expose:
      - "5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "puta@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "puta"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    container_name: pgadmin-com
    volumes:
      - ../pgadmin:/var/lib/pgadmin
    networks:
      - net

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

volumes:
  local_pgdata:
  pgadmin-data:
